names_to_ru = {
    'person': 'человек',
    'bicycle': 'велосипед',
    'car': 'машина',
    'cell phone': 'смартфон',
    'bottle': 'бутылка',
    'toothbrush': 'зубная щетка',
    'chair': 'кресло',
    'couch': 'диван',
    'potted plant': 'растение',
    'bed': 'кровать',
    'dining table': 'стол',
    'tv': 'телевизор',
    'laptop': 'ноутбук',
    'mouse': 'мышь',
    'remote': 'пульт',
    'keyboard': 'клавиатура',
    'microwave': 'микроволновка',
}